### ISSUE TITLE
Arm64v8 + Python 3.8.2 Arg Issue

### ISSUE THREAD

**Issue by bandwiches** [leamas/ddupdate#44] opened 2020-07-02 14:25 UTC
Hi!

I ran into an issue installing via Pip.  When passing --list-services or --list-addresses it would automatically issue a dry-run without listing service or address plugins.

```
xxx@yyy:~/ddns$ ddupdate --list-services
WARNING - Cannot open config file '/etc/ddupdate.conf' for read
INFO - Loglevel: INFO
INFO - Using hostname: host.nowhere.net
INFO - Using ip address plugin: default-if
INFO - Using service plugin: dry-run
INFO - Service options:
INFO - Address options:
xxx@yyy:~/ddns$ ddupdate -S
WARNING - Cannot open config file '/etc/ddupdate.conf' for read
INFO - Loglevel: INFO
INFO - Using hostname: host.nowhere.net
INFO - Using ip address plugin: default-if
INFO - Using service plugin: dry-run
INFO - Service options:
INFO - Address options:
```

I actually launched a python 3.8.3-alpine container on the same machine and it worked just fine, so I just chalked it up to it being an issue with the older version but I wanted to make you aware in case it was something bigger.  Thanks!

**Comment by bandwiches** [comment] 2020-07-02 14:27
I also noticed I was referencing --list-addresses instead of --list-addressers but got the same result.

**Comment by leamas** [comment] 2020-08-13 17:00
Hi,

Been on  a long, Nordic summer holiday, sorry for delay. 

Looks strange. What OS:version are you using on your Arm64v8  when you get the error? In particular, what is the python version?

**Comment by bandwiches** [comment] 2020-08-13 18:58
Hey there!  Good question, I'm not entirely sure what version of Python but I can say with certainty it was some derivative of 3.8 (could have been 3.8.3 or 3.8.7 or 3.8.8 - those are the ones I was using around that time).  OS version would be Ubuntu 20.04 LTS Server x64.

**Comment by leamas** [comment] 2020-08-13 19:14
Hm... I have an ubuntu 20.04 desktop VM available. Using that, I cannot reproduce the problem. It's using python 3.8.2

More questions: did  you install the pip package system-wide or as a regular user?  What does` which ddupdate` tell us?

**Comment by bandwiches** [comment] 2020-08-19 16:14
I believe it to be system-wide.  Architecture was on ARMx64 (Raspberry PI 4 B+; 4GB) if that helps, not sure if your VM is desktop or ARM

**Comment by leamas** [comment] 2020-08-19 18:11
If there is a difference in  a pure python application between arm and x86_64 we will need to file a bug against python. It 's IMHO not the first option.

I tend to think that you had two installations when you tested. The symptoms matches exactly this -- you installed something, but when you invoked 'ddupdate'  you actually ran another version. Perhaps a packaged one, or another pypi install done as a regular user.

**Comment by bandwiches** [comment] 2020-08-22 16:41
I support that.  Sorry I don't have more information to give, I hate leaving things open

**Comment by leamas** [comment] 2020-08-24 06:19
I'm closing this as WORKSFORME. Please reopen if appropriate.

**Closed as completed by leamas** 2020-08-24 06:19 UTC
